package jamming

import (
	"time"

	"github.com/0xciph3r/lnaudit/pkg/scanner"
)

// Confidence represents evidence quality for a jamming signal.
type Confidence string

const (
	ConfidenceObserved     Confidence = "observed"
	ConfidenceSustained    Confidence = "sustained"
	ConfidenceCorroborated Confidence = "corroborated"
)

// AttackClass identifies the dominant jamming pattern.
type AttackClass string

const (
	ClassSlotPressure      AttackClass = "slot_pressure"
	ClassLiquidityPressure AttackClass = "liquidity_pressure"
	ClassCorroboratedJam   AttackClass = "corroborated_jam"
)

// ChannelSample captures the metrics needed for temporal jamming analysis.
type ChannelSample struct {
	ChanID              uint64 `json:"chan_id"`
	RemotePubkey        string `json:"remote_pubkey"`
	CapacitySat         int64  `json:"capacity_sat"`
	LocalBalanceSat     int64  `json:"local_balance_sat"`
	RemoteBalanceSat    int64  `json:"remote_balance_sat"`
	PendingHTLCCount    int    `json:"pending_htlc_count"`
	PendingHTLCValueSat int64  `json:"pending_htlc_value_sat"`
	RemoteMaxHTLCs      uint32 `json:"remote_max_htlcs"`
}

// Snapshot is a point-in-time view of channel metrics.
type Snapshot struct {
	Timestamp time.Time       `json:"timestamp"`
	Channels  []ChannelSample `json:"channels"`
}

// Timeline is an ordered sequence of snapshots.
type Timeline struct {
	Snapshots []Snapshot `json:"snapshots"`
}

// Finding is a temporal analysis result generated by the analyzer.
type Finding struct {
	ID          string                 `json:"id"`
	Class       AttackClass            `json:"class"`
	Severity    scanner.Severity       `json:"severity"`
	Confidence  Confidence             `json:"confidence"`
	ChannelID   uint64                 `json:"channel_id,omitempty"`
	Title       string                 `json:"title"`
	Description string                 `json:"description"`
	Evidence    map[string]interface{} `json:"evidence"`
}

// Options controls analyzer thresholds and output behavior.
type Options struct {
	SlotSaturationThreshold      float64
	LiquiditySaturationThreshold float64
	MinSustainedSamples          int
	EmitObserved                 bool
}

// DefaultOptions returns conservative, deterministic defaults.
func DefaultOptions() Options {
	return Options{
		SlotSaturationThreshold:      0.60,
		LiquiditySaturationThreshold: 0.60,
		MinSustainedSamples:          3,
		EmitObserved:                 false,
	}
}

func normalizeOptions(opts Options) Options {
	d := DefaultOptions()
	if opts.SlotSaturationThreshold > 0 && opts.SlotSaturationThreshold <= 1 {
		d.SlotSaturationThreshold = opts.SlotSaturationThreshold
	}
	if opts.LiquiditySaturationThreshold > 0 && opts.LiquiditySaturationThreshold <= 1 {
		d.LiquiditySaturationThreshold = opts.LiquiditySaturationThreshold
	}
	if opts.MinSustainedSamples >= 2 {
		d.MinSustainedSamples = opts.MinSustainedSamples
	}
	d.EmitObserved = opts.EmitObserved
	return d
}
